### ISSUE TITLE
pressing buttons does not do anything inside remote window

### ISSUE THREAD

**Issue by Abu3safeer** [komefai/PS4Macro.Remote#2] opened 2017-12-15 08:12 UTC
Hello, 
I bought several DS4 but sony make low quality ones, beside they are expensive.
so I was looking for method to use Mouse and Keyboard to play using remote play.
so I found your app here, but looks like it does not affect the remote window.
once I press play inside PS4Macro buttons mapping window popup, but no button affect Remote Play window, even the arrows (they move through menus normally), arrows don't affect it after pressing play.

**Comment by komefai** [comment] 2017-12-16 17:05
Hi! Glad you found this project. It seems like the keyboard hooking works fine but the problem comes from failing to inject to Remote Play. Just to be sure, did you try it while a DS4 is plugged in? If not then I recommend you to first try the app again while DS4 is connected and working correctly with PS4 Remote Play. 

If it works then you can try using it without DS4 plugged in by setting `<EmulateController>` to true in [settings.xml](https://github.com/komefai/PS4Macro#settings).

**Comment by Abu3safeer** [comment] 2017-12-16 17:31
I play with the controller all time, but tried it again just to make sure, and it worked.
so I created a new settings.xml file with these info:
 <?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AutoInject>true</AutoInject>
  <EmulateController>true</EmulateController>
  <ShowConsole>true</ShowConsole>
  <StartupFile>PS4Macro.Remote.dll</StartupFile>
</Settings>

and ran the app:
![image](https://user-images.githubusercontent.com/12091003/34072838-92a466d8-e29f-11e7-878c-3f5c4ce70948.png)
these two windows pop up, the DS4 still working even with the app running, but all my keyboard buttons do not work, whatever I press, nothing happens.
but once I close the app I can press arrows to navigate in menus only. 

by the way every time I click play I see this window:
![image](https://user-images.githubusercontent.com/12091003/34072866-f9a2b9c0-e29f-11e7-8293-40361fa2a464.png)

every single time.

**Comment by komefai** [comment] 2017-12-16 18:04
Thanks for the screenshots! Please try restarting PS4 Remote Play once and set the 3 values in settings.xml to false first to see if it works. If it still doesn’t work I’ll come up with a new method to test your problem.

The window you see when you press play is normal. It’s for configuration so you can close it or leave it in the background.

**Comment by Abu3safeer** [comment] 2017-12-16 19:00
I have set all three values to false then restarted both the app and PS4 remote app.
then launched PS4 remote app, then ran PS4Macro app, before I press play I tried to navigate to see if arrows buttons still work before injection, and they worked, then clicked play icon and its color changed to green, after that tried to navigate but no button works now.
so what do you think? 

EDIT: even if I click stop button (the square) no button work at all, but if I close PS4Macro app arrow buttons work again, so looks like after injection no button work.

**Comment by komefai** [comment] 2017-12-17 04:31
I see, let’s try this instead. Start PS4 Macro and click File->New to reset it to macro mode. Then click on the record button follow by play (they should turn to red and green respectively). If everything is working properly, the red number on the bottom right should keep increasing.

This should help us narrow down the problem. By the way don’t worry about the arrow keys not working because it is an expected behavior (since we are intercepting/overriding the key press and remapping it to some other key).

**Comment by Abu3safeer** [comment] 2017-12-17 05:50
Do you mean like this:
https://streamable.com/vad60

**Comment by komefai** [comment] 2017-12-17 06:03
Yes! Thanks for the video. Now we know for sure that the problem is the injection routine making the app failed to intercept the DS4 controls.

Can you try what you did in the video again with PS4Macro v0.3.1? Make sure to start+stream remote play before running otherwise it will cause an error in that version.

**Comment by Abu3safeer** [comment] 2017-12-17 14:02
as you can see in the video, in v0.3.1 it has the same issue, beside I can move arrows (which not possible in v0.4.0
https://streamable.com/06hjn

**Comment by komefai** [comment] 2017-12-18 09:49
Download [PS4RemotePlayInterceptorDemo.zip](https://github.com/komefai/PS4Macro.Remote/files/1567347/PS4RemotePlayInterceptorDemo.zip) and run `PS4RemotePlayInterceptorDemo.exe` then click on **Inject**. When it fails, it should give you an error message that will help us with the problem. You can take a screenshot of the result and send it to me.

**Comment by Abu3safeer** [comment] 2017-12-18 13:46
If I click inject directly it throws this message:
failed to inject to target: Exception has been thrown by the target of an invocation.
my windows language is Arabic so I see the message on Arabic, but I looked for it and found it here:
http://finderr.net/clr/ar/%D8%AA%D9%85-%D8%B7%D8%B1%D8%AD-%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7%D8%A1-%D8%A8%D9%88%D8%A7%D8%B3%D8%B7%D8%A9-%D9%87%D8%AF%D9%81-%D8%A7%D8%B3%D8%AA%D8%AF%D8%B9%D8%A7%D8%A1-/1306111086
so I think this is the right translation.

BUT...

if I click inject again I see the PID: 13724 which is the number of RemotePlay.exe process.
now it is already injected and I see "Stop" button, if I click stop and inject again I will see the same error message, but when I click inject again it show the PID.

so the short is, click -> error -> stop, click ->injected -> stop ,,, Again.

**Comment by komefai** [comment] 2017-12-19 00:12
Thanks. Please try again with this one instead. 
[PS4RemotePlayInterceptorDemo.zip](https://github.com/komefai/PS4Macro.Remote/files/1569844/PS4RemotePlayInterceptorDemo.zip)

It should show 2 error messages with a lot more detail. Send me a screenshot of both.

**Comment by Abu3safeer** [comment] 2017-12-19 00:24
the same error message with some details:
![image](https://user-images.githubusercontent.com/12091003/34134494-f3262730-e46b-11e7-8e0a-816ad9dee0c8.png)
![image](https://user-images.githubusercontent.com/12091003/34134510-0f2b978a-e46c-11e7-9dbd-922a5d656799.png)

**Comment by komefai** [comment] 2017-12-19 00:35
Awesome! Here's my attempt to fixing the problem and make sure to Run As Admin. If it works then you will not see any errors and your left analog stick will be forced upwards.

[Debug.zip](https://github.com/komefai/PS4Macro.Remote/files/1569868/Debug.zip)

**Comment by Abu3safeer** [comment] 2017-12-19 00:38
it shows no error, but nothing happened to PS4RemotePlay, I thought it will start to move up.
should I plugin my ps4 controller or something?

**Comment by komefai** [comment] 2017-12-19 00:41
Yes, for testing purposes please plug a DS4 in and restart both the app again. To be sure verify that DS4 is actually controlling the game before starting `PS4RemotePlayInterceptorDemo.exe`.

**Comment by Abu3safeer** [comment] 2017-12-19 00:51
I plugged my DS4 and restarted PS4Remote, then I checked that controller controls everything.
then I ran PS4RemotePlayInterceptorDemo.exe. as Admin, once I clicked injected it was moving up + press X, and when I stop injecting PS4Remote craches.

**Comment by komefai** [comment] 2017-12-19 01:02
Okay, it's working and now I know exactly what the problem is, so this is what you should do to make PS4Macro work.

In **settings.xml** always use `<AutoInject>false</AutoInject>` because your system seems to not support the feature but that is fine. When running **PS4Macro.exe**, always run as admin.

Now if you want to use it without a DS4 plugged in, set `<EmulateController>true</EmulateController>`, but you have to start at this screen.

![emulatecontrollerps4](https://user-images.githubusercontent.com/30201667/34135369-da55133e-e492-11e7-94e7-6cf7c616ad55.png)

**Closed as completed by komefai** 2017-12-19 01:02 UTC

**Comment by Abu3safeer** [comment] 2017-12-19 01:12
I edited settings.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AutoInject>false</AutoInject>
  <EmulateController>true</EmulateController>
  <ShowConsole>false</ShowConsole>
  <StartupFile>PS4Macro.Remote.dll</StartupFile>
</Settings>
```
I started PS4Remote then PS4 as admin and see the second image (OK),, I click run, then enter my ps4, then press ASDW buttons to navigate but nothing happens, but I can navigate using arrows.

is there something wrong?

**Comment by Abu3safeer** [comment] 2017-12-19 01:16
I tried again with DS4 plugged in, with the same settings, 
after running PS4Macro and pressing play button no keyboard button response (even arrows), but I can still control with my DS4.

**Comment by komefai** [comment] 2017-12-19 01:19
Sorry I forgot to mention. Do what you just did previously, but without DS4 plugged in because **you cannot have a DS4 plugged in when EmulateController is set to true**. 

If you don't mind plugging in a DS4 while controlling with your keyboard you can set EmulateController to false and leave it plugged in.

**Comment by Abu3safeer** [comment] 2017-12-19 01:29
didn't work, 

in picture 'OK' I should see the small message telling me to press OPTIONS button, so I pressed ALT (as it represents OPTIONS, but didn't work at all, keep in mind that I don't have DS4 plugged in + EmulateController set to true.

**Comment by komefai** [comment] 2017-12-19 01:33
You're very close, once it turns in to the 'OK' picture, you can press Start with your mouse.

**Comment by Abu3safeer** [comment] 2017-12-19 01:34
isn't should work as controller emulated on that menu? because no buttons work at all inside PS4 screen.

**Comment by Abu3safeer** [comment] 2017-12-19 01:37
Oh it worked, I had to press Play button several times, looks like it does not inject properly first time.

**Comment by komefai** [comment] 2017-12-19 01:37
This menu is using a different method of reading inputs than the one inside the PS4 screen. It is like a "slow reading" to save power when you're in that menu, the real reading starts when you're inside the PS4 screen.
